### ISSUE TITLE
Bug with first lines of code in documentation?

### ISSUE THREAD

**Issue by lee-hodg** [disqus/disqus-python#23]
I installed disqus-python then tried the basic example with my secret key and public key:

```
pip install disqus-python
from disqusapi import DisqusAPI
disqus = DisqusAPI(secret_key, public_key)
```

However now when I do

```
disqus.get('trends.listThreads')
```

I get the error:

```
TypeError: __call__() takes exactly 1 argument (2 given)
```

**Comment by nehiljain** [comment]
Fix not pushed yet? IS there an alternative?

**Comment by rmtew** [comment]
pip install disqus-python still installs a version that errors as above.

  File "update.py", line 70, in run_disqus
    for result in disqus.get("posts.list", forum="myforum"):
TypeError: __call__() takes exactly 1 argument (3 given)

**Comment by svengt** [comment]
+1

**Comment by loneboat** [comment]
+1

**Comment by mxrss** [comment]
@loneboat 

I had luck by following the directions here

https://github.com/disqus/disqus-python/issues/22

What you need to do is do a pip install of this

> pip install https://github.com/disqus/disqus-python/archive/master.zip

**Comment by aktivkohle** [comment]
Am using Python 3. The error changed to 
`InterfaceNotDefined: Interface is not defined, you must pass ``method`` (HTTP Method).`
...after I redid pip install from the git master. 

@fpghost suggestion above
`for result in disqus.get('trends.listThreads', method='GET'):`
fixed it (thanks!) now it is nicely returning threads. Would be handy if this missing bit of code was in the original README.rst

**Comment by martinosorb** [comment]
2018 here, still not fixed. This is really badly maintained.
